CREATE TABLE IF NOT EXISTS game (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    id_twitch BIGINT UNSIGNED NOT NULL,
    box_art_url VARCHAR(255) NOT NULL,
    igdb_id BIGINT UNSIGNED,
    create_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE (id_twitch)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS views (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_twitch BIGINT UNSIGNED NOT NULL,
    views BIGINT UNSIGNED NOT NULL,
    create_at DATETIME NOT NULL,

    PRIMARY KEY (id)
) ENGINE=MyISAM;

CREATE INDEX idx_create_at ON views(create_at);